### ISSUE TITLE
Linter/CSSlint doesn't not flagging any errors

### ISSUE THREAD

**Issue by BMOv2600** [AtomLinter/linter-csslint#30] opened 2015-07-10 00:50 UTC
Config: 

```
linter:
    lintOnFly: true
    showErrorPanel: false
```

New API is in /packages/linter/package.json. 

SCSS in linter-plus.less is identical to default.

Not linting/writing any other languages, so I'm not sure if it's an issue with linter-csslint or AtomLinter. Do I need to post on their issues?

**Comment by steelbrain** [comment] 2015-07-25 09:50
Dupe of #29

**Closed by steelbrain** 2015-07-25 09:50 UTC
