### ISSUE TITLE
LinterCsslint.Linter is deprecated.

### ISSUE THREAD

**Issue by hagom** [AtomLinter/linter-csslint#31] opened 2015-07-13 01:30 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
LinterCsslint.Linter (/home/hagom/.atom/packages/linter/lib/linter.coffee:60:4)
new LinterCsslint (/home/hagom/.atom/packages/linter-csslint/lib/linter-csslint.coffee:28:4)
Object.lint (/home/hagom/.atom/packages/linter/lib/legacy.coffee:61:21)
<unknown> (/home/hagom/.atom/packages/linter/lib/editor-linter.coffee:69:25)
currentLinter (/home/hagom/.atom/packages/linter/lib/editor-linter.coffee:68:19)
<unknown> (/home/hagom/.atom/packages/linter/lib/editor-linter.coffee:82:22)
```

**Comment by TWHarr** [comment] 2015-07-14 18:25
I am having this same issue.

**Comment by salvimateus** [comment] 2015-07-17 19:26
+1

**Comment by z3ntu** [comment] 2015-07-18 16:25
bump

**Comment by steelbrain** [comment] 2015-07-21 23:00
Dupe of #29

**Closed by steelbrain** 2015-07-21 23:00 UTC
