### ISSUE TITLE
maybe it's a problem

### ISSUE THREAD

**Issue by xlc1540697096** [AtomLinter/linter-csslint#168] opened 2017-08-09 08:36 UTC
```
[Linter] Error running CSSLint Error: (node:8488) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: processFile(...).then is not a function
(node:8488) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at ChildProcess.<anonymous> (C:\Users\win10\.atom\packages\linter-csslint\node_modules\sb-exec\lib\index.js:56)
    at emitTwo (events.js:106)
    at ChildProcess.emit (events.js:191)
    at maybeClose (internal/child_process.js:885)
    at Socket.<anonymous> (internal/child_process.js:334)
    at emitOne (events.js:96)
    at Socket.emit (events.js:188)
    at Pipe._handle.close [as _onclose] (net.js:501)
(anonymous) @ linter-registry.js:137
```

**Comment by xlc1540697096** [comment] 2017-08-09 08:42
And my code is shaking continuously!

**Comment by kurtschlatzer** [comment] 2017-08-09 14:57
It's definitely a problem:

```
/Users/xxxxxxx/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running CSSLint Error: (node:25058) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: processFile(...).then is not a function
(node:25058) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at ChildProcess.<anonymous> (/Users/xxxxxxx/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
(anonymous) @ /Users/xxxxxxx/.atom/packages/linter/lib/linter-registry.js:159
```

**Comment by Arcanemagus** [comment] 2017-08-09 15:54
Duplicate of #166.

**Closed by Arcanemagus** 2017-08-09 15:54 UTC
