### ISSUE TITLE
Ignores .csslintrc file in project folder

### ISSUE THREAD

**Issue by martinkr** [AtomLinter/linter-csslint#12] opened 2014-10-23 16:25 UTC
Without the possibility to place a .csslintrc inside the project root i can not figure out how this plugin should be usefull. I have multiple projects with different rules. This is a common setup. And ist's best practice to have all your .*rc files in your projects root. See jshint, jsbeautifier, gitignore, etc
Please integrate this :)

**Comment by AlexanderOMara** [comment] 2015-04-14 17:14
+1

I would like to see this also.

**Comment by kylewelsby** [comment] 2015-07-07 04:45
duplicate of #8

**Comment by steelbrain** [comment] 2015-07-25 09:51
Merging into #29

**Closed by steelbrain** 2015-07-25 09:51 UTC
