### ISSUE TITLE
Linter-csslint does not work on windows 10

### ISSUE THREAD

**Issue by clang676** [AtomLinter/linter-csslint#157] opened 2016-11-28 18:22 UTC
This linter does not work at all on any windows OS.

linter-csslint Version: 1.3.3
Atom Version: 1.12.6

**Comment by Arcanemagus** [comment] 2016-11-28 19:01
Duplicate of #156, it's not Windows 10 but the terrible `csslint` code breaking in recent Atom versions 😛.

**Closed by Arcanemagus** 2016-11-28 19:01 UTC
Labels: duplicate
