### ISSUE TITLE
Package Loading slow

### ISSUE THREAD

**Issue by wackywendell** [AtomLinter/linter-csslint#67] opened 2015-12-15 16:34 UTC
I have 124 Atom packages in Atom, and `linter-csslint` is the slowest to load out of all of them: it takes 109ms to load, even when no project is opened and so no CSS files are in the workspace.

Could `linter-csslint` possibly do something like [lazy loading](https://github.com/atom/atom/issues/2654#issuecomment-46518588)?

**Comment by Arcanemagus** [comment] 2015-12-15 17:20
Atom has `activationHooks` to solve this, unfortunately they are currently pretty buggy, a fix for this will be in the v1.4.0 branch (It's already in v1.4.0-beta0).

As soon as that gets pushed to stable I plan on moving _all_ of the linter plugin packages to that model so they will only activate if you are loading a file of a language they support.

(Also you should think about switching to a different CSS linter like `linter-stylelint`, `csslint` itself hasn't seen any development for almost a year now and appears to be abandoned, I'm keeping this wrapper running for now but things currently don't look hopeful for `csslint`.)

**Comment by Arcanemagus** [comment] 2015-12-15 17:26
Also lazy loading in the manner you linked wouldn't work as the package needs to register a service, not run a command itself.

There are probably a few things that could be done to speed up the current start up and I would happily review a PR for them but for the moment until v1.4.0 lands on stable I have no plans to implement this myself.

**Comment by dirk-thomas** [comment] 2016-02-11 07:49
@wackywendell Can you please try the latest code in development mode since PR #78 should improve the situation and report back the latest status. Thanks.

**Comment by wackywendell** [comment] 2016-02-11 14:20
Hmm... I just tried opening and closing Atom in development mode 10 times, first with 1.2.0, and then with master. I modified master slightly so that it reported a package number as 1.2.1, so that I could be sure it was loading master. With 1.2.0, I got an activation time of 40±2 ms, and with master, 55±15 ms. Maybe that difference is just noise... but I am not seeing much of an improvement. ☹ @dirk-thomas, were you seeing an improvement? Am I missing something?

**Comment by Arcanemagus** [comment] 2016-02-11 17:34
A few things here: The time reported in timecop is the activation time while all other packages are _also_ loading, so it will be pretty variable depending on when Atom decides to start loading it.

The slower activation time that #78 fixes only affects the _very first_ package to call `require('atom-package-deps').install()` with no parameters (~30 ms time), subsequent calls are quite fast (~2 ms). So if you had a package calling that before this one did during startup you would see no difference from #78.

**Comment by dirk-thomas** [comment] 2016-02-11 18:43
@Arcanemagus I don't think #78 only affect the activation time of the very first package. It also delays requiring the other dependencies (`atom-linter`, `path`).

@wackywendell For me the activation of this package without the patch (the hash before the patch was applied 31fbebc6f32f90c8d3923d8d4143b2f17d5e273d) is around 45 - 55 ms. With the patch applied it goes down to 30 - 35 ms. Both was measured in development mode.

Both times are significantly faster if you only install the necessary dependencies and avoid installing the dev dependencies. So for non-development mode when installing the latest package version through atom (which doesn't install the dev dependencies) that would be the case.

@Arcanemagus Maybe you can provide some feedback why the pure existence of the dev dependencies in the `node_modules` folder impact the activation so negatively?

**Comment by Arcanemagus** [comment] 2016-02-11 19:20
I have no idea why the devDependencies being present would affect the activation time :open_mouth:, @steelbrain?

I wonder if Atom is scanning all the folders in the dir for some reason? Recent versions of `npm` attempt to install the `node_modules` folder as "flat" as possible, while old versions (and thus `apm` install it hierarchically). If you do `npm install --only=prod` is the loading time the same as `apm install`?

**Comment by steelbrain** [comment] 2016-02-11 23:42
@Arcanemagus Having devDependencies present shouldn't affect activation time at all, not from my current understanding of the Node.js docs at least

**Comment by dirk-thomas** [comment] 2016-02-12 05:54
For comparison I fetched the latest state of this package (33dbf16927968550163b36aa04e5aadc9a11d55b) and put it into the `dev/packages` folder. For the record this is with Atom 1.5.1. The activation time is *very* different depending on which node modules are installed:
* after `npm install --only=prod` it is either shown with 6ms or not listed (which implies 5ms or even faster)
  * `npm list | wc -l` output 16
* after `npm install` it takes 20 - 35 ms which is significantly slower!!!
  * `npm list | wc -l` output 271 just to give a rough comparison on the amount of installed node modules

Can anybody reproduce this? If yes, should this be reported somewhere else since I don't think how this would be related to `linter-csslint` itself?

**Comment by Arcanemagus** [comment] 2016-02-12 18:43
Okay, I think I've discovered the difference @dirk-thomas: You are testing with `atom --dev` :stuck_out_tongue:

All testing was done on a blank profile, other than `linter-csslint` and `linter` (since it gets installed automatically). There was one more combination that could have been tested, which is `linter-csslint` installed from within the Atom package manager interface (equivalent to `apm install --only=prod` I'm guessing), but the spreadsheet was already large enough, and it wouldn't really affect the results in any major way :wink:.

From the [timing data](https://docs.google.com/spreadsheets/d/1XkYcoIk9bCMo-WtAttYXrgsVilHfTmvAAPT_8Kei0Nc/edit?usp=sharing) from my tests you can see the following:

* At no point did `linter-csslint`'s activation time pass the 5ms monitoring threshold
* Development packages being installed makes no difference unless Atom is launched with `atom --dev`, in which case `linter-csslint`'s _loading_ time is greatly increased, but activation time remains unchanged
* The hierarchical folder structure from `apm install` ("`npm` v2.13.3") is actually _slower_ than `npm` (v3.3.12) flat structure, even though far more directories are in the root, it doesn't have to process as many levels to find the packages it needs.
* `linter` itself seems like it could use some work, as it took ~40 ms to activate

**Comment by dirk-thomas** [comment] 2016-02-12 18:53
My measurements are showing the opposite of what you mention in the second bullet though. Starting `atom -dev` *does* increase the activation time for me. I would need to double check but I am pretty sure that load time was not affected at all.

**Comment by Arcanemagus** [comment] 2016-02-12 19:03
Oh, forgot to mention that I'm testing on Atom 1.6.0-beta2.

Bullet point 2 says nothing about activation times, only package loading times. (I never once saw an activation time over 5ms, so I have no data on it...)

**Comment by dirk-thomas** [comment] 2016-02-12 19:04
Even when you follow my exact steps to install `linter-csslint` in dev mode you don't see a higher activation time??

**Comment by Arcanemagus** [comment] 2016-02-12 19:08
As stated I tested on a blank profile, with the only packages installed being `linter-csslint` and `linter`. (I'm not sure if this is a bug or not but `atom --dev` was loading all my normal packages as well, so I created a blank profile.)

**Comment by dirk-thomas** [comment] 2016-02-13 17:10
My previous response was based on misunderstanding on of the earlier comments. I have updated https://github.com/AtomLinter/linter-csslint/issues/67#issuecomment-183448941 to clarify it.

My performance "problem" is solved by #78 and using `npm install --only=prod` when running in development mode. Thanks @Arcanemagus for the detailed responses.

I will let @wackywendell comment what remains the issue for him.

**Comment by Arcanemagus** [comment] 2016-02-14 09:26
@dirk-thomas I think I just figured out a large bit of confusion here between what I have been saying and what you have been seeing: Are you using the `This package added ___ms to startup time.` text from a package's info page for your number?

That is a combination of the loading and activation times that TimeCop shows, if you check the spreadsheet I linked you can see what each individual bit contributes to this total time that is shown in the package info.

**Comment by dirk-thomas** [comment] 2016-02-15 19:34
No, I was only looking at the `Activation time` column in TimeCop. But thanks for the pointer - I didn't now that the settings page of each package shows the combined times.

**Comment by Arcanemagus** [comment] 2016-02-15 19:41
That's just bizarre, `atom` vs `atom --dev` shouldn't have changed your activation time, only the loading time :confused:.

**Comment by dirk-thomas** [comment] 2016-02-15 19:58
I am pretty sure I saw the activation being increased last times I tried. I actually restarted it multiple time to get average timings. :worried: I also updated Atom to the latest patch release in between (even if I don't think it matters it makes it a less stable test).

Yet today I see what you are describing all the time. Only in development mode and when the dev dependencies are installed I see this package listed in the "loading" column in TimeCop with +-25ms.

**Comment by Arcanemagus** [comment] 2017-08-26 06:55
The changes in #170 should bring "activation time" down below 5 ms on most machines, depending on how busy Atom is loading other packages.

Any further optimization would require moving to the `activationHooks`, which although we have figured out how to do properly and still have usable specs, requires maintenance of the list of languages to activate on so it's a very low priority.

**Closed** 2017-08-26 07:05 UTC
Labels: enhancement
