### ISSUE TITLE
[Linter] Error running CSSLint

### ISSUE THREAD

**Issue by zvemaxim** [AtomLinter/linter-csslint#169] opened 2017-08-23 18:48 UTC
[Linter] Error running CSSLint Error: (node:1117) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: processFile(...).then is not a function
(node:1117) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at ChildProcess.<anonymous> (/Users/mx/.atom/packages/linter/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
(anonymous) @ /Users/mx/.atom/packages/linter/lib/linter-registry.js:159

**Comment by zvemaxim** [comment] 2017-08-23 18:49
What does it mean? Has anybody a way to fix it?

**Comment by Arcanemagus** [comment] 2017-08-23 19:24
It means that I haven't had time to fix this package, and nobody that actually uses it has bothered to take the time either 😛.

I very much recommend switching to [stylelint](https://stylelint.io/) ([linter-stylelint](https://atom.io/packages/linter-stylelint)) as CSSLint itself has been essentially abandoned. For more information though see the following issue.

**Comment by Arcanemagus** [comment] 2017-08-23 19:24
Duplicate of #166

**Closed by Arcanemagus** 2017-08-23 19:24 UTC

**Comment by cshanejennings** [comment] 2017-08-23 19:36
@Arcanemagus Thanks for that.  Maybe consider putting that recommendation in the README just to keep your inbox sane?  I'm good because I was following this thread, but it's probably going to be raining support tickets all day otherwise?  Cheers mate!

**Comment by zvemaxim** [comment] 2017-08-23 19:54
Thank you!

23 авг. 2017 г. 22:36 пользователь "Shane Jennings" <
notifications@github.com> написал:

**Comment by Arcanemagus** [comment] 2017-08-23 20:09
@cshanejennings Unfortunately the CSSLint team hasn't officially announced they have stopped working on it, and _occasionally_ they will put out a tiny fix here and there. So it's not as simple as being able to say "go use this other thing" directly in the README like that.

**Comment by cshanejennings** [comment] 2017-08-23 23:37
Ah right, gotcha.  No worries!
