### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, NaN)

### ISSUE THREAD

**Issue by robneu** [AtomLinter/linter-csslint#37] opened 2015-08-06 17:29 UTC
This is related to https://github.com/atom-community/linter/issues/804 but seems to be a problem primarily with this linter.

Steps to Reproduce:

1. Open a CSS file.

**Atom Version**: 1.0.4
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.2

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65

TypeError: Invalid Point: (NaN, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:970:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:958:20)
    at TextBuffer.module.exports.TextBuffer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:683:46)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1406:41)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1272:59)
    at /Users/robertneu/.atom/packages/linter/lib/linter-views.coffee:207:64
    at Array.forEach (native)
    at LinterViews.renderPanelMarkers (/Users/robertneu/.atom/packages/linter/lib/linter-views.coffee:201:20)
    at LinterViews.render (/Users/robertneu/.atom/packages/linter/lib/linter-views.coffee:76:12)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "one-dark-ui",
      "base16-eighties-one-dark"
    ]
  },
  "linter": {
    "statusIconPosition": "Right",
    "showErrorTabProject": false,
    "showErrorTabLine": true,
    "showErrorInline": false,
    "statusIconScope": "File"
  }
}
```

### Installed Packages

```coffee
# User
atom-minify, v0.2.2
atom-wordpress, v0.3.0
base16-eighties-one-dark, v0.2.2
docblockr, v0.7.3
file-icons, v1.6.2
highlight-selected, v0.10.1
line-ending-converter, v1.2.0
linter, v1.3.2
linter-csslint, v1.0.1
linter-jscs, v2.0.4
linter-jshint, v1.1.4
linter-jsonlint, v0.1.4
linter-php, v1.0.3
linter-phpcs, v1.0.6
linter-scss-lint, v2.0.0
minimap, v4.12.2
minimap-pigments, v0.1.3
php-debug, v0.1.2
pigments, v0.9.3
project-manager, v1.15.11
sync-settings, v0.6.0
tabs-to-spaces, v0.11.0
trailing-spaces, v0.3.2
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by robmarston** [comment] 2015-08-06 19:54
+1

**Comment by Arcanemagus** [comment] 2015-08-06 21:22
Looks like this is caused by the linter returning a message with no line numbers... I'll put a PR in that just forces it to be at the start of the file if no line number could be determined.

----
Specifically
```
Too many floats (10), you're probably using them for layout. Consider using a grid system instead.
```

**Comment by Arcanemagus** [comment] 2015-08-06 23:54
The fix for this should be in v1.0.2, can you verify it works for you?

**Comment by robneu** [comment] 2015-08-07 02:18
Not working yet over here.

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.2


### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65

TypeError: Invalid Point: (NaN, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:970:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:958:20)
    at TextBuffer.module.exports.TextBuffer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:683:46)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1406:41)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1272:59)
    at /Users/robertneu/.atom/packages/linter/lib/linter-views.coffee:207:64
    at Array.forEach (native)
    at LinterViews.renderPanelMarkers (/Users/robertneu/.atom/packages/linter/lib/linter-views.coffee:201:20)
    at LinterViews.render (/Users/robertneu/.atom/packages/linter/lib/linter-views.coffee:76:12)
```

**Comment by Arcanemagus** [comment] 2015-08-07 03:41
Do you have some code to reproduce this with?

**Comment by robneu** [comment] 2015-08-07 05:07
So far this is the only bit of code I've managed to isolate as being an issue. Guessing it's related to the vendor prefix?

```css
@-webkit-keyframes featherlightLoader {
	0% {
		-webkit-transform: rotate(0deg);
		transform: rotate(0deg);
	}

	100% {
		-webkit-transform: rotate(360deg);
		transform: rotate(360deg);
	}
}
```

**Comment by Arcanemagus** [comment] 2015-08-07 05:15
Are you sure your `linter-csslint` is at v1.0.2? This shows no issues for me (and definitely doesn't crash).

**Comment by robneu** [comment] 2015-08-07 05:19
Yup. Latest of both the linter and the `linter-csslint` package. It only fails when the file is  first opened. Once that first error occurs, linting of the rest of the file fails completely with a message of `Fatal error, cannot continue: Cannot read property 'push' of undefined at line NaN col NaN`

**Comment by Arcanemagus** [comment] 2015-08-07 05:21
Can you try closing Atom, renaming your `.atom` folder to `.atom.bak` (or something similar), starting Atom back up and installing `linter` and `linter-csslint` to see if it's an installation issue?

**Comment by Arcanemagus** [comment] 2015-08-07 05:25
If it is still broken on the fresh profile please open up the developer tools and put a breakpoint at line 33 in csslint's main.coffee, lint a file and see what the _ref object looks like?

**Comment by robneu** [comment] 2015-08-07 05:26
Nope, same issue with a fresh install. Here's the [full file](https://github.com/wpsitecare/wp-featherlight/blob/develop/css/wp-featherlight.css) that's causing the failure if it's helpful.

I'll check that object now...

**Comment by Arcanemagus** [comment] 2015-08-07 05:27
Ah, I'm getting it on the full file. I'll see what can be done to fix it!

**Comment by robneu** [comment] 2015-08-07 05:41
I assume you've already seen it, but the `_ref` object looks like:

```
ef: Array[1]
0: Object
message: "Fatal error, cannot continue: Cannot read property 'push' of undefined"
rule: Object
type: "error"
__proto__: Object
length: 1
__proto__: Array[0]
```
I wish I could be more help, but debugging JS is pretty far from one of my strong points. LoL

**Comment by Arcanemagus** [comment] 2015-08-07 07:56
Okay, https://github.com/AtomLinter/linter-csslint/pull/39 stops making any assumptions, and causes the linter to "work" for your file. _But_ it seems csslint itself has an internal error on your file, which is what that message is coming from and so why it's so badly formed.

In any case, `linter-csslint` shouldn't trigger this error once that gets merged.

**Comment by Arcanemagus** [comment] 2015-08-07 17:24
@robneu Can you verify this is not longer causing a crash in the linter in v1.0.5? Also somebody should probably file an issue on `csslint` about this bug... although I'm not too hopeful because development on it seems to have stagnated.

**Comment by Arcanemagus** [comment] 2015-08-07 17:29
@robmarston since you `+1`d this, are you still seeing any issues in [v1.0.5](13abf0d0bd806404c76f3c6f553b5a4a51c3b625)?

**Comment by robneu** [comment] 2015-08-07 17:34
Everything looks good for me. Do you have any idea what the problem is with that file exactly?

**Comment by robmarston** [comment] 2015-08-07 17:35
Sorry for the delay @Arcanemagus, I wanted to give @robneu a chance to respond. No issues for me, thanks for all the hard work!

**Comment by Arcanemagus** [comment] 2015-08-07 17:41
From the quick look into the `csslint` code I took my guess would be the part that generates the message list assumes an object is an array but it is in fact undefined, and _somehow_ the error gets pushed in as the message text.

I can try diagnosing it and figuring out a fix Monday evening, but I'll be busy till then.

Since this issue seems to be fixed I'm marking it as closed, please feel free to open this back up if you see any other instances of this occurring.

**Closed by Arcanemagus** 2015-08-07 17:41 UTC

**Comment by robneu** [comment] 2015-08-07 17:42
Sounds good. Thanks for figuring it out so quickly! :100:

**Comment by Arcanemagus** [comment] 2015-08-10 16:05
@inacent You reported that you were still seeing this on v1.0.5, do you have code to reproduce this with?
