### ISSUE TITLE
Error running CSSLint

### ISSUE THREAD

**Issue by shillem** [AtomLinter/linter-csslint#166] opened 2017-08-09 07:22 UTC
I'm using atom 1.19.
When linting any css file I get the error mentioned in the subject.
The console reads:

```
[Linter] Error running CSSLint Error: (node:75225) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: processFile(...).then is not a function
(node:75225) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at ChildProcess.<anonymous> (/Users/shillem/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by dutchauser** [comment] 2017-08-09 13:39
Hi, I'm running the same version of Atom and I am having the same issues.

**Comment by Arcanemagus** [comment] 2017-08-09 17:07
I think I'm just going to completely remove the ability to lint on the fly and switch this package to executing  `csslint` as an external process. This will also allow switching to the official build which is necessary as nobody has stepped up to take over maintaining this package or the fork of `csslint` that it depends on (since `csslint` hasn't merged support for `stdin` text themselves...).

**Comment by dertin** [comment] 2017-08-09 19:48
Same
```
[Linter] Error running CSSLint Error: (node:10115) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: processFile(...).then is not a function
(node:10115) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at ChildProcess.<anonymous> (/Users/gcespedes/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by eddvq** [comment] 2017-08-09 20:17
Having the same issues too.

**Comment by bdsexton** [comment] 2017-08-09 22:21
I have been running into this error too—every time I preview, open, modify, or save a CSS file. It happens whether I modify CSS rules or comments.

<img width="464" alt="error running csslint" src="https://user-images.githubusercontent.com/656157/29146132-9c0aa7be-7d14-11e7-8e67-11a1ceed3fc6.png"> × ∞

I am running Atom 1.19.0 x64 on macOS Sierra 10.12.6. I have not checked any other versions or operating systems.

**Comment by Arcanemagus** [comment] 2017-08-09 23:44
This is a **known issue**, please stop posting "me too". The potential solutions are outlined in my [earlier comment](https://github.com/AtomLinter/linter-csslint/issues/166#issuecomment-321318907). If somebody wants to work on a PR for that I would be happy to review it, otherwise I will try to get to it sometime tomorrow.

I would _highly_ recommend you switch to using [stylelint](https://stylelint.io/) ([linter-stylelint](https://atom.io/packages/linter-stylelint)) as CSSLint has been essentially abandoned.

**Comment by bdsexton** [comment] 2017-08-10 02:55
@Arcanemagus People have just been trying to help by confirming that the issue is not isolated and by providing potentially relevant details. There is no need for discourtesy.

**Comment by Arcanemagus** [comment] 2017-08-10 06:28
Would you like to become a maintainer here to help take care of issues and maintain the package? This package hasn't had an active maintainer in a _very_ long time and it would be great if somebody who actually uses this provider and could give it the attention it deserves would take it on.

**Comment by jsejcksn** [comment] 2017-08-10 07:43
@bdsexton I agree that most people are probably doing just as you described, but it contributes to [noise](https://en.wikipedia.org/wiki/Signal-to-noise_ratio) due to the redundancy, requiring more effort from anyone trying to skim for actual information.

Most people are probably just unaware that they can use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to [vote](https://github.com/isaacs/github/issues/9) and that they can [subcribe](https://help.github.com/articles/subscribing-to-conversations/) to issues without commenting.

Now, the _reason(s)_ that they might be unaware... might deserve a more intense emotional reaction.

@Arcanemagus How spot on am I?

**Comment by Arcanemagus** [comment] 2017-08-10 19:06
@jsejcksn Very spot on, thank you 😉.

**Comment by vnt** [comment] 2017-08-11 14:54
I have the same problem:

[Linter] Error running CSSLint
See Console for more info. (Open View -> Developer -> Toggle Developer Tools)

I am running Atom 1.19.0 x64 on macOS Sierra 10.12.6.

**Comment by mingjunyang** [comment] 2017-08-18 08:26
same too problem.


```shell

Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0


├── linter@2.2.0
├── linter-csslint@1.3.4
```

error info
```text
[Linter] Error running CSSLint Error: (node:11408) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: processFile(...).then is not a function
(node:11408) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at ChildProcess.<anonymous> ($HOME/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:56)
    at emitTwo (events.js:106)
    at ChildProcess.emit (events.js:191)
    at maybeClose (internal/child_process.js:885)
    at Socket.<anonymous> (internal/child_process.js:334)
    at emitOne (events.js:96)
    at Socket.emit (events.js:188)
    at Pipe._handle.close [as _onclose] (net.js:501)
(anonymous) @ linter-registry.js [sm]:137
```

**Comment by bdsexton** [comment] 2017-08-18 10:10
@Arcanemagus: Thank you for the stylelint and linter-stylelint recommendations. They seem great.

**Comment by Arcanemagus** [comment] 2017-08-26 03:02
Well unfortunately it looks like nobody is interested in taking on maintenance of this package, so I'm going to have to move forward with the plan of removing support for linting on changes by switching this package back to using the master `csslint` fork. Hopefully will have a fix up in a bit!

**Comment by abstractmachines** [comment] 2017-08-26 04:40
Thanks for your work @Arcanemagus

**Closed** 2017-08-26 07:05 UTC
Labels: bug

**Comment by samguergen** [comment] 2018-01-18 16:37
I want to completely uninstall csslint. Remove this error message and just forget about the whole thing. How do I do that? I ran npm uninstall csslint but it doesn't work

**Comment by Arcanemagus** [comment] 2018-01-18 19:43
@samguergen Since you are commenting on an issue in a repository for an Atom package, I'm going to assume you are using Atom and have `linter-csslint` installed. You can uninstall that from within Atom's Settings under the Packages section, or by typing `apm uninstall linter-csslint` in a terminal.

**Comment by lavander99x** [comment] 2020-04-02 09:48
i use Atom and also has the same problem as well, the main file i wrote to build the body of the website name index.html and the file i paste all code of css name style.css, after hit save on style.css , it's said that Error running CSS lint, just because my file index.html not the same level as well as the style.css, we must fix it to make they all the same level
