### ISSUE TITLE
LinterShellcheck.Linter is deprecated.

### ISSUE THREAD

**Issue by ApfelUser** [AtomLinter/linter-csslint#32] opened 2015-07-21 15:55 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/atom-community/linter/wiki/Migrating-to-the-new-API
```
LinterCsslint.Linter (/Users/apfeluser/.atom/packages/linter/lib/linter.coffee:60:4)
new LinterCsslint (/Users/apfeluser/.atom/packages/linter-csslint/lib/linter-csslint.coffee:28:4)
Object.lint (/Users/apfeluser/.atom/packages/linter/lib/legacy.coffee:61:21)
<unknown> (/Users/apfeluser/.atom/packages/linter/lib/editor-linter.coffee:69:25)
currentLinter (/Users/apfeluser/.atom/packages/linter/lib/editor-linter.coffee:68:19)
<unknown> (/Users/apfeluser/.atom/packages/linter/lib/editor-linter.coffee:82:22)
```

**Comment by steelbrain** [comment] 2015-07-21 23:01
Dupe of #29

**Closed by steelbrain** 2015-07-21 23:01 UTC
