### ISSUE TITLE
Can't install linter-csslint

### ISSUE THREAD

**Issue by tomas1000r** [AtomLinter/linter-csslint#41] opened 2015-08-11 21:52 UTC
npm ERR! git fetch -a origin (https://github.com/AtomLinter/csslint) fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\Users\\test\\AppData\\Local\\atom\\app-1.0.5\\resources\\app\\apm\\bin\\node.exe" "c:\\Users\\test\\AppData\\Local\\atom\\app-1.0.5\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\test\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\test\\.atom\\.apmrc" "install" "C:\\Users\\test\\AppData\\Local\\Temp\\d-115711-5456-1uewekn\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by tomas1000r** [comment] 2015-08-11 21:53
It looks like a repository is not pointing to correct location of linter-csslint

**Comment by Arcanemagus** [comment] 2015-08-12 03:15
Duplicate of https://github.com/AtomLinter/linter-csslint/issues/40, although I'm not sure what a good solution to this is since we can't use regular `csslint`...

**Comment by Arcanemagus** [comment] 2015-10-01 16:14
Closing this as any discussion on solving this should be done in #40.

**Closed by Arcanemagus** 2015-10-01 16:14 UTC
